jobs:
  redis:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      dockerFile: docker/redis/redis.dockerfile
      dockerImageName: redis
      dockerContextDirectory: docker/redis
    readyStateText: starting workers
